"""Excel report generation using openpyxl."""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, Optional

from openpyxl import Workbook
from openpyxl.styles import (
    Font,
    PatternFill,
    Alignment,
    Border,
    Side,
    DEFAULT_FONT,
    numbers,
)
from openpyxl.utils import get_column_letter
from openpyxl.utils.dataframe import dataframe_to_rows
import pandas as pd

logger = logging.getLogger(__name__)


class ExcelReportGenerator:
    """Generate Excel reports with multiple sheets and formatting."""

    def __init__(self, title: str = "Data Analysis Report"):
        self.title = title
        self.workbook = Workbook()
        self.workbook.remove(self.workbook.active)

    def generate(
        self,
        report_data: dict[str, Any],
        output_path: Optional[str] = None,
    ) -> Optional[bytes]:
        """Generate Excel report."""
        try:
            self._create_summary_sheet(report_data)
            self._create_data_sheet(report_data)
            self._create_statistics_sheet(report_data)
            self._create_findings_sheet(report_data)

            if output_path:
                self.workbook.save(output_path)
                logger.info(f"✅ Excel report saved to {output_path}")
                return None
            else:
                import io

                buffer = io.BytesIO()
                self.workbook.save(buffer)
                return buffer.getvalue()

        except Exception as e:
            logger.error(f"❌ Error generating Excel report: {e}")
            raise

    def _create_summary_sheet(self, report_data: dict[str, Any]) -> None:
        """Create summary sheet."""
        ws = self.workbook.create_sheet("Summary", 0)

        ws["A1"] = f"Report: {report_data.get('title', self.title)}"
        ws["A1"].font = Font(bold=True, size=14, color="FFFFFF")
        ws["A1"].fill = PatternFill(
            start_color="2e5c8a", end_color="2e5c8a", fill_type="solid"
        )
        ws.merge_cells("A1:D1")
        ws["A1"].alignment = Alignment(horizontal="center", vertical="center")

        row = 3
        metadata = [
            ("Report Date", datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
            ("Generated By", report_data.get("generated_by", "InsightFlow AI")),
            ("Total Records", f"{report_data.get('total_rows', 0):,}"),
            ("Columns", str(report_data.get("column_count", 0))),
            ("Quality Score", f"{report_data.get('quality_score', 0):.1f}%"),
            ("Completeness", f"{report_data.get('completeness', 0):.1f}%"),
        ]

        for label, value in metadata:
            ws[f"A{row}"] = label
            ws[f"B{row}"] = value
            ws[f"A{row}"].font = Font(bold=True)
            ws[f"A{row}"].fill = PatternFill(
                start_color="d9e1f2", end_color="d9e1f2", fill_type="solid"
            )
            row += 1

        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 35

        row += 2
        ws[f"A{row}"] = "Summary"
        ws[f"A{row}"].font = Font(bold=True, size=12)
        row += 1

        summary = report_data.get("summary", "No summary available.")
        ws.merge_cells(f"A{row}:D{row + 3}")
        summary_cell = ws[f"A{row}"]
        summary_cell.value = summary
        summary_cell.alignment = Alignment(wrap_text=True, vertical="top")
        summary_cell.fill = PatternFill(
            start_color="f0f0f0", end_color="f0f0f0", fill_type="solid"
        )

    def _create_data_sheet(self, report_data: dict[str, Any]) -> None:
        """Create data sheet."""
        df = report_data.get("dataframe")
        if df is None or (isinstance(df, pd.DataFrame) and df.empty):
            return

        ws = self.workbook.create_sheet("Data", 1)

        for col_idx, col_name in enumerate(df.columns, 1):
            cell = ws.cell(row=1, column=col_idx)
            cell.value = col_name
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill(
                start_color="2e5c8a", end_color="2e5c8a", fill_type="solid"
            )
            cell.alignment = Alignment(horizontal="center")

        for row_idx, (_, row_data) in enumerate(df.iterrows(), 2):
            for col_idx, value in enumerate(row_data, 1):
                cell = ws.cell(row=row_idx, column=col_idx)
                cell.value = value

                if isinstance(value, (int, float)):
                    if isinstance(value, float):
                        cell.number_format = "#,##0.00"
                    else:
                        cell.number_format = "#,##0"

                if row_idx % 2 == 0:
                    cell.fill = PatternFill(
                        start_color="f0f0f0", end_color="f0f0f0", fill_type="solid"
                    )

        for col_idx in range(1, len(df.columns) + 1):
            max_length = len(str(df.columns[col_idx - 1])) + 2
            for row_idx in range(2, min(len(df) + 2, 100)):
                cell_value = ws.cell(row=row_idx, column=col_idx).value
                max_length = max(max_length, len(str(cell_value)) + 1)

            ws.column_dimensions[get_column_letter(col_idx)].width = min(max_length, 50)

    def _create_statistics_sheet(self, report_data: dict[str, Any]) -> None:
        """Create statistics sheet."""
        statistics = report_data.get("statistics", {})
        if not statistics:
            return

        ws = self.workbook.create_sheet("Statistics", 2)

        ws["A1"] = "Statistical Summary"
        ws["A1"].font = Font(bold=True, size=12, color="FFFFFF")
        ws["A1"].fill = PatternFill(
            start_color="2e5c8a", end_color="2e5c8a", fill_type="solid"
        )
        ws.merge_cells("A1:C1")

        row = 3
        ws["A2"] = "Metric"
        ws["B2"] = "Value"
        ws["C2"] = "Description"

        for col in ["A", "B", "C"]:
            ws[f"{col}2"].font = Font(bold=True)
            ws[f"{col}2"].fill = PatternFill(
                start_color="d9e1f2", end_color="d9e1f2", fill_type="solid"
            )

        for key, value in list(statistics.items())[:50]:
            ws[f"A{row}"] = str(key)
            ws[f"B{row}"] = value
            ws[f"C{row}"] = report_data.get("statistic_descriptions", {}).get(key, "")

            if isinstance(value, float):
                ws[f"B{row}"].number_format = "#,##0.00"
            elif isinstance(value, int):
                ws[f"B{row}"].number_format = "#,##0"

            if row % 2 == 0:
                for col in ["A", "B", "C"]:
                    ws[f"{col}{row}"].fill = PatternFill(
                        start_color="f0f0f0", end_color="f0f0f0", fill_type="solid"
                    )

            row += 1

        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 20
        ws.column_dimensions["C"].width = 30

    def _create_findings_sheet(self, report_data: dict[str, Any]) -> None:
        """Create findings sheet."""
        findings = report_data.get("key_findings", [])
        recommendations = report_data.get("recommendations", [])

        if not findings and not recommendations:
            return

        ws = self.workbook.create_sheet("Findings", 3)

        row = 1

        if findings:
            ws[f"A{row}"] = "Key Findings"
            ws[f"A{row}"].font = Font(bold=True, size=12, color="FFFFFF")
            ws[f"A{row}"].fill = PatternFill(
                start_color="2e5c8a", end_color="2e5c8a", fill_type="solid"
            )
            ws.merge_cells(f"A{row}:B{row}")
            row += 1

            for i, finding in enumerate(findings[:20], 1):
                ws[f"A{row}"] = f"{i}."
                ws[f"B{row}"] = finding
                ws[f"B{row}"].alignment = Alignment(wrap_text=True)
                row += 1

            row += 1

        if recommendations:
            ws[f"A{row}"] = "Recommendations"
            ws[f"A{row}"].font = Font(bold=True, size=12, color="FFFFFF")
            ws[f"A{row}"].fill = PatternFill(
                start_color="2e5c8a", end_color="2e5c8a", fill_type="solid"
            )
            ws.merge_cells(f"A{row}:B{row}")
            row += 1

            for i, rec in enumerate(recommendations[:20], 1):
                ws[f"A{row}"] = f"{i}."
                ws[f"B{row}"] = rec
                ws[f"B{row}"].alignment = Alignment(wrap_text=True)
                row += 1

        ws.column_dimensions["A"].width = 3
        ws.column_dimensions["B"].width = 80
