"""PDF report generation service using ReportLab."""

from __future__ import annotations

import io
import logging
from datetime import datetime
from typing import Any, Optional

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    Image,
    KeepTogether,
    Preformatted,
)
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
import pandas as pd

logger = logging.getLogger(__name__)


class PDFReportGenerator:
    """Generate professional PDF reports with charts and data."""

    def __init__(
        self, title: str = "Data Analysis Report", filename: str = "report.pdf"
    ):
        self.title = title
        self.filename = filename
        self.pagesize = letter
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()

    def _add_custom_styles(self) -> None:
        """Add custom paragraph styles."""
        self.styles.add(
            ParagraphStyle(
                name="CustomHeading1",
                parent=self.styles["Heading1"],
                fontSize=24,
                textColor=colors.HexColor("#1f4788"),
                spaceAfter=20,
                alignment=TA_CENTER,
                fontName="Helvetica-Bold",
            )
        )

        self.styles.add(
            ParagraphStyle(
                name="CustomHeading2",
                parent=self.styles["Heading2"],
                fontSize=16,
                textColor=colors.HexColor("#2e5c8a"),
                spaceAfter=12,
                spaceBefore=12,
                fontName="Helvetica-Bold",
            )
        )

        self.styles.add(
            ParagraphStyle(
                name="CustomBody",
                parent=self.styles["Normal"],
                fontSize=11,
                alignment=TA_JUSTIFY,
                spaceAfter=12,
                leading=14,
            )
        )

        self.styles.add(
            ParagraphStyle(
                name="MetaInfo",
                parent=self.styles["Normal"],
                fontSize=9,
                textColor=colors.HexColor("#666666"),
                alignment=TA_LEFT,
            )
        )

    def generate(
        self,
        report_data: dict[str, Any],
        output_path: Optional[str] = None,
    ) -> bytes:
        """Generate PDF report and return bytes."""
        output_path = output_path or self.filename
        doc = SimpleDocTemplate(
            output_path,
            pagesize=self.pagesize,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=0.75 * inch,
        )

        story = []
        story.extend(self._build_title_section(report_data))
        story.extend(self._build_metadata_section(report_data))
        story.append(PageBreak())
        story.extend(self._build_executive_summary_section(report_data))
        story.extend(self._build_key_findings_section(report_data))
        story.append(PageBreak())
        story.extend(self._build_statistics_section(report_data))
        story.extend(self._build_data_section(report_data))
        story.append(PageBreak())
        story.extend(self._build_recommendations_section(report_data))
        story.extend(self._build_footer_section(report_data))

        doc.build(story)

        if output_path:
            with open(output_path, "rb") as f:
                return f.read()

        return b""

    def _build_title_section(self, report_data: dict[str, Any]) -> list:
        """Build title page section."""
        story = []

        title_text = report_data.get("title", self.title)
        story.append(Paragraph(title_text, self.styles["CustomHeading1"]))
        story.append(Spacer(1, 0.3 * inch))

        subtitle = report_data.get("subtitle", "Data Analysis Report")
        story.append(Paragraph(subtitle, self.styles["Heading2"]))
        story.append(Spacer(1, 0.5 * inch))

        org_name = report_data.get("organization", "InsightFlow AI")
        story.append(
            Paragraph(f"<b>Organization:</b> {org_name}", self.styles["CustomBody"])
        )
        story.append(Spacer(1, 0.2 * inch))

        return story

    def _build_metadata_section(self, report_data: dict[str, Any]) -> list:
        """Build metadata section."""
        story = []

        story.append(Paragraph("Report Information", self.styles["CustomHeading2"]))

        metadata = [
            ["Field", "Value"],
            ["Report Date", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            ["Generated By", report_data.get("generated_by", "InsightFlow AI")],
            ["Total Records", f"{report_data.get('total_rows', 0):,}"],
            ["Columns", str(report_data.get("column_count", 0))],
            ["Data Quality Score", f"{report_data.get('quality_score', 0):.1f}%"],
            ["Completeness", f"{report_data.get('completeness', 0):.1f}%"],
        ]

        table = Table(metadata, colWidths=[2 * inch, 3 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2e5c8a")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 11),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, colors.HexColor("#f0f0f0")],
                    ),
                    ("TOPPADDING", (0, 1), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
                ]
            )
        )

        story.append(table)
        story.append(Spacer(1, 0.3 * inch))

        return story

    def _build_executive_summary_section(self, report_data: dict[str, Any]) -> list:
        """Build executive summary section."""
        story = []

        story.append(Paragraph("Executive Summary", self.styles["CustomHeading2"]))

        summary = report_data.get("summary", "No summary available.")
        story.append(Paragraph(summary, self.styles["CustomBody"]))
        story.append(Spacer(1, 0.2 * inch))

        return story

    def _build_key_findings_section(self, report_data: dict[str, Any]) -> list:
        """Build key findings section."""
        story = []

        findings = report_data.get("key_findings", [])
        if not findings:
            return story

        story.append(Paragraph("Key Findings", self.styles["CustomHeading2"]))

        for i, finding in enumerate(findings[:10], 1):
            text = f"<b>{i}.</b> {finding}"
            story.append(Paragraph(text, self.styles["CustomBody"]))
            story.append(Spacer(1, 0.1 * inch))

        story.append(Spacer(1, 0.2 * inch))
        return story

    def _build_statistics_section(self, report_data: dict[str, Any]) -> list:
        """Build statistics section."""
        story = []

        statistics = report_data.get("statistics", {})
        if not statistics:
            return story

        story.append(Paragraph("Statistics", self.styles["CustomHeading2"]))

        table_data = [["Metric", "Value", "Description"]]
        for key, value in list(statistics.items())[:15]:
            if isinstance(value, (int, float)):
                formatted = (
                    f"{value:,.2f}" if isinstance(value, float) else f"{value:,}"
                )
            else:
                formatted = str(value)

            description = report_data.get("statistic_descriptions", {}).get(key, "")
            table_data.append([str(key), formatted, description])

        table = Table(table_data, colWidths=[2 * inch, 1.5 * inch, 1.5 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2e5c8a")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, colors.HexColor("#f0f0f0")],
                    ),
                ]
            )
        )

        story.append(table)
        story.append(Spacer(1, 0.3 * inch))

        return story

    def _build_data_section(self, report_data: dict[str, Any]) -> list:
        """Build data table section."""
        story = []

        df = report_data.get("dataframe")
        if df is None or (isinstance(df, pd.DataFrame) and df.empty):
            return story

        story.append(Paragraph("Sample Data", self.styles["CustomHeading2"]))

        table_data = [list(df.columns)]
        for idx, row in df.head(10).iterrows():
            table_data.append([str(v)[:30] for v in row.values])

        col_count = len(df.columns)
        col_width = (5 * inch) / col_count if col_count > 0 else 1

        table = Table(table_data, colWidths=[col_width] * col_count)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2e5c8a")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, colors.HexColor("#f0f0f0")],
                    ),
                ]
            )
        )

        story.append(table)
        story.append(Spacer(1, 0.1 * inch))

        if len(df) > 10:
            story.append(
                Paragraph(f"Showing 10 of {len(df)} records", self.styles["MetaInfo"])
            )

        story.append(Spacer(1, 0.3 * inch))
        return story

    def _build_recommendations_section(self, report_data: dict[str, Any]) -> list:
        """Build recommendations section."""
        story = []

        recommendations = report_data.get("recommendations", [])
        if not recommendations:
            return story

        story.append(Paragraph("Recommendations", self.styles["CustomHeading2"]))

        for i, rec in enumerate(recommendations[:10], 1):
            text = f"<b>{i}.</b> {rec}"
            story.append(Paragraph(text, self.styles["CustomBody"]))
            story.append(Spacer(1, 0.1 * inch))

        story.append(Spacer(1, 0.2 * inch))
        return story

    def _build_footer_section(self, report_data: dict[str, Any]) -> list:
        """Build footer section."""
        story = []

        story.append(Spacer(1, 0.3 * inch))
        footer_text = "This report was automatically generated by InsightFlow AI. Please review all data and findings before making decisions."
        story.append(Paragraph(footer_text, self.styles["MetaInfo"]))

        return story
